# Generated by Django 5.2.7 on 2026-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_game_options_game_created_at_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Процент скидки (0-100)', verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатная игра'),
        ),
    ]
